[DEVICE_INFO]
name = 
path = 
filesystem = 
model = 
total_size_bytes = 
device = 
serial_number = None
total = 0
used = 0
free = 0
human_total = 0 B
human_used = 0 B
human_free = 0 B
disk_type = ssd

[BACKUP]
automatically_backup = false
backing_up = false
status = 

[EXCLUDE]
exclude_hidden_itens = true

[BACKUP_FOLDERS]
folders = 

[PIP]
commands = pip install requests,pip install numpy pandas,cargo install ripgrep

[SEARCH]
need_refresh_database = false

